apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - namespace.yaml
configMapGenerator:
  - name: argocd-values
    files:
      - values.yaml=argocd-values.yaml
configurations:
  - kustomizeconfig.yaml