apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - namespace.yaml
configMapGenerator:
  - name: kube-prom-values
    files:
      - values.yaml=kube-prom-values.yaml
configurations:
  - kustomizeconfig.yaml