apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./argocd
  - ../../base/ingress-nginx
  - ../../base/flux-1
  # - ../../base/kube-prom-stack
  # - ../../base/limit-range
  # - ../../base/metric-server
  # - ../../base/node-local-dns
patches:
  - path: env-k3s.yaml