global:
  domain: "argocd-staging.makegorka.com"

configs:
  rbac:
    policy.csv: |
      p, role:egorka,  applications, *,    default/*, allow
      g, egorka,       role:egorka
  secret:
    ## `htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'`
    argocdServerAdminPassword: "$2a$10$S9W13ON6U81tq34kNcuf5unw1NamBEKnyrRn.eocP5Q07rQ0Qcy5a"
    extra:
      accounts.egorka.password: "$2a$10$1pExcDjnIfOsPIOd.Zk3jO9.gTH88FbGOtzhZpMsv8hSBoY/Wkv3K"
