apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../../base/argocd
secretGenerator:
  - name: argocd-secret-env
    files:
      - argocd-secret-env=argocd-secret.yaml
patches:
  - path: hr-release.yaml
configurations:
  - kustomizeconfig.yaml