apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-crd
  namespace: argocd
spec:
  interval: 30m0s
  path: ./manifests/crds
  prune: true
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: argocd-crd
  targetNamespace: argocd
  timeout: 3m0s
  wait: true
