apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./argocd
  - ../../base/ingress-nginx
  - ../../base/kube-prom-stack
  - ../../base/metric-server
  - ../../base/limit-range
  - ../../base/node-local-dns
patches:
  - path: env-egorka.yaml